import { getAllPublications } from "./publications";
// Pure scoring logic lives in searchClient.js (browser-safe, no Node imports).
// Re-exported here so server code can use a single import path if needed.
export { searchIndex } from "./searchClient";


const PUBLICATION_KINDS = {
  project:    "Project",
  "case-study": "Case Study",
  lab:        "Lab",
  research:   "Research Note",
};

/**
 * Builds the full search index at build time / layout render time.
 *
 * Each entry:
 *   { id, kind, type, title, slug, url, tags, technologies, domain,
 *     excerpt, status, readingTime, evidenceTypes }
 *
 * kind = "publication" | "page" | "type-filter"
 */
export function buildSearchIndex() {
  const publications = getAllPublications();

  const publicationEntries = publications.map((pub) => ({
    id: `pub:${pub.type}:${pub.slug}`,
    kind: "publication",
    type: pub.type,
    typeLabel: PUBLICATION_KINDS[pub.type] ?? pub.type,
    title: pub.title,
    slug: pub.slug,
    url: `/publications/${pub.type}/${pub.slug}`,
    tags: pub.tags || [],
    technologies: pub.technologies || [],
    domain: pub.domain || "",
    excerpt: pub.summary || "",
    status: pub.status || "complete",
    readingTime: pub.readingTime || "",
    // Index evidence types so you can search "terminal" or "pcap"
    evidenceTypes: (pub.evidence || []).map((e) => e.type),
  }));

  const pageEntries = [
    {
      id: "page:home",
      kind: "page",
      type: "page",
      typeLabel: "Page",
      title: "Home",
      url: "/",
      tags: ["home", "briefing", "identity"],
      technologies: [],
      domain: "",
      excerpt: "The briefing — engineering identity, current focus, featured work.",
      status: "complete",
      readingTime: "",
      evidenceTypes: [],
    },
    {
      id: "page:publications",
      kind: "page",
      type: "page",
      typeLabel: "Page",
      title: "Publications Index",
      url: "/publications",
      tags: ["publications", "index", "all"],
      technologies: [],
      domain: "",
      excerpt: "Master index of all engineering publications.",
      status: "complete",
      readingTime: "",
      evidenceTypes: [],
    },
    {
      id: "page:systems",
      kind: "page",
      type: "page",
      typeLabel: "Page",
      title: "Technology & Systems Map",
      url: "/systems",
      tags: ["systems", "technology", "taxonomy", "skills"],
      technologies: [],
      domain: "",
      excerpt: "Taxonomy of engineering domains and tools cross-linked to publications.",
      status: "complete",
      readingTime: "",
      evidenceTypes: [],
    },
    {
      id: "page:about",
      kind: "page",
      type: "page",
      typeLabel: "Page",
      title: "About & Methodology",
      url: "/about",
      tags: ["about", "methodology", "author", "colophon"],
      technologies: [],
      domain: "",
      excerpt: "Engineering background, methodology principles, contact.",
      status: "complete",
      readingTime: "",
      evidenceTypes: [],
    },
    {
      id: "page:resume",
      kind: "page",
      type: "page",
      typeLabel: "Page",
      title: "Resume & Curriculum Vitae",
      url: "/resume",
      tags: ["resume", "cv", "hire", "curriculum vitae", "experience", "credentials", "pdf"],
      technologies: [],
      domain: "",
      excerpt: "Professional resume of Taiwo Olumide — print-ready A4/Letter CV and verified competencies.",
      status: "complete",
      readingTime: "",
      evidenceTypes: [],
    },
  ];

  // Type-filter shortcuts — allow "type:lab" or just "labs" to jump to filter
  const typeFilterEntries = Object.entries(PUBLICATION_KINDS).map(([id, label]) => ({
    id: `filter:${id}`,
    kind: "type-filter",
    type: id,
    typeLabel: "Filter",
    title: `Browse ${label}s`,
    url: `/publications?type=${id}`,
    tags: [id, label.toLowerCase(), "filter", "browse"],
    technologies: [],
    domain: "",
    excerpt: `View all ${label.toLowerCase()} publications.`,
    status: "complete",
    readingTime: "",
    evidenceTypes: [],
  }));

  // Theme switching — discoverable via command palette
  const themeEntries = [
    { id: "dark",       name: "Dark",       tags: ["dark", "black", "default"] },
    { id: "light",      name: "Light",      tags: ["light", "white", "bright"] },
    { id: "midnight",   name: "Midnight",   tags: ["midnight", "github", "dark"] },
    { id: "terminal",   name: "Terminal",   tags: ["terminal", "green", "hacker", "unix"] },
    { id: "paper",      name: "Paper",      tags: ["paper", "warm", "cream", "sepia"] },
    { id: "nord",       name: "Nord",       tags: ["nord", "arctic", "blue"] },
    { id: "dracula",    name: "Dracula",    tags: ["dracula", "purple", "vampire"] },
    { id: "catppuccin", name: "Catppuccin", tags: ["catppuccin", "mocha", "pastel"] },
    { id: "gruvbox",    name: "Gruvbox",    tags: ["gruvbox", "retro", "warm", "amber"] },
    { id: "solarized",  name: "Solarized",  tags: ["solarized", "ocean", "teal"] },
  ].map((t) => ({
    id: `theme:${t.id}`,
    kind: "theme",
    type: "theme",
    typeLabel: "Theme",
    title: `Switch to ${t.name}`,
    url: null,
    action: { type: "theme", value: t.id },
    tags: ["theme", "appearance", ...t.tags],
    technologies: [],
    domain: "",
    excerpt: `Apply the ${t.name} color theme.`,
    status: "complete",
    readingTime: "",
    evidenceTypes: [],
  }));

  const fontEntries = [
    { id: "editorial", name: "Editorial",  tags: ["editorial", "instrument", "sans"] },
    { id: "geist",     name: "Geist",      tags: ["geist", "vercel", "modern"] },
    { id: "system",    name: "System",     tags: ["system", "inter", "default"] },
    { id: "ibm",       name: "IBM Plex",   tags: ["ibm", "plex", "monospaced"] },
    { id: "fraunces",  name: "Fraunces",   tags: ["fraunces", "serif", "decorative"] },
    { id: "space",     name: "Space",      tags: ["space", "grotesk", "geometric"] },
    { id: "dm",        name: "DM",         tags: ["dm", "sans", "clean"] },
    { id: "fira",      name: "Fira Code",  tags: ["fira", "code", "ligatures"] },
  ].map((f) => ({
    id: `font:${f.id}`,
    kind: "font",
    type: "font",
    typeLabel: "Font",
    title: `Use ${f.name} typography`,
    url: null,
    action: { type: "font", value: f.id },
    tags: ["font", "typography", ...f.tags],
    technologies: [],
    domain: "",
    excerpt: `Switch to the ${f.name} font pairing.`,
    status: "complete",
    readingTime: "",
    evidenceTypes: [],
  }));

  const quickActionEntries = [
    {
      id: "action:resume",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "View & Print Resume (CV)",
      url: "/resume",
      tags: ["resume", "cv", "hire", "curriculum vitae", "pdf", "print", "credentials"],
      technologies: [],
      domain: "",
      excerpt: "Open print-ready curriculum vitae with verified technical competencies.",
      action: { type: "navigate", url: "/resume" },
      shortcut: "R",
    },
    {
      id: "action:copy-email",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "Copy Contact Email (nicocipherr@gmail.com)",
      url: null,
      tags: ["email", "contact", "copy", "hire", "reach out", "mail"],
      technologies: [],
      domain: "",
      excerpt: "Copy direct contact email to clipboard with instant confirmation.",
      action: { type: "copy-email", value: "nicocipherr@gmail.com" },
      shortcut: "E",
    },
    {
      id: "action:filter-networking",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "Filter Publications: Networking & OSPF",
      url: "/publications?domain=networking",
      tags: ["networking", "cisco", "ospf", "vlans", "switching", "arp"],
      technologies: ["Cisco IOS", "OSPF", "VLANs"],
      domain: "networking",
      excerpt: "Browse enterprise switching, VLANs, and OSPF publications.",
      action: { type: "navigate", url: "/publications?domain=networking" },
      shortcut: "N",
    },
    {
      id: "action:filter-infrastructure",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "Filter Publications: Infrastructure & Linux",
      url: "/publications?domain=infrastructure",
      tags: ["infrastructure", "linux", "active directory", "sssd", "systemd", "server"],
      technologies: ["Ubuntu", "Active Directory", "SSSD"],
      domain: "infrastructure",
      excerpt: "Browse Active Directory integration and headless Linux deployments.",
      action: { type: "navigate", url: "/publications?domain=infrastructure" },
      shortcut: "I",
    },
    {
      id: "action:filter-security",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "Filter Publications: Cybersecurity",
      url: "/publications?domain=security",
      tags: ["security", "cybersecurity", "cookie", "threat modeling", "owasp", "auth"],
      technologies: ["OWASP", "DevTools"],
      domain: "security",
      excerpt: "Browse session hijacking, threat modeling, and defensive controls.",
      action: { type: "navigate", url: "/publications?domain=security" },
      shortcut: "S",
    },
    {
      id: "action:filter-labs",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "Filter Publications: Hands-on Labs",
      url: "/publications?type=lab",
      tags: ["labs", "hands-on", "troubleshooting", "experiments"],
      technologies: [],
      domain: "",
      excerpt: "View all reproducible lab guides with verified configurations.",
      action: { type: "navigate", url: "/publications?type=lab" },
      shortcut: "L",
    },
    {
      id: "action:toggle-theme",
      kind: "quick-action",
      type: "action",
      typeLabel: "Action",
      title: "Toggle Color Theme (Dark / Light)",
      url: null,
      tags: ["theme", "dark", "light", "toggle", "mode", "appearance"],
      technologies: [],
      domain: "",
      excerpt: "Switch between dark and light color modes.",
      action: { type: "toggle-theme" },
      shortcut: "T",
    },
  ];

  return [
    ...quickActionEntries,
    ...pageEntries,
    ...publicationEntries,
    ...typeFilterEntries,
    ...themeEntries,
    ...fontEntries,
  ];
}
